FROM python:3.8.3-alpine3.11 as builder

ARG GID=503
ARG UID=503

RUN if [ $(grep ":${GID}:" /etc/group | wc -l) == 0 ]; then addgroup -S -g ${GID} bxextensions; fi

RUN if [ $(grep ":${UID}:" /etc/passwd | wc -l) == 0 ]; then adduser -u ${UID} -S -g ${GID} bxextensions; fi  && \
    mkdir -p /app/bxextensions && \
    chown -R ${UID}:${GID} /app/bxextensions

RUN apk update \
 && apk add --no-cache \
# grab su-exec for easy step-down from root
    'su-exec>=0.2' \
    tini \
    # grab bash for the convenience
    bash \
    # grab requirements for bxextenstions
    gcc libc-dev unixodbc-dev make \
    build-base \
    gfortran \
    python3 \
    libc6-compat \
    freetype-dev \
    openblas-dev \
    tcl \
    tk \
    python3-dev \
    pkgconfig \
    musl \
    libgfortran \
    libgcc \
    automake \
    # autogen \
    autoconf \
    libtool \
    # libtool-bin \
    openssl-dev \
    cmake \
    libexecinfo-dev

#upgrade pip
RUN pip3 install --upgrade pip setuptools

COPY docker-entrypoint.sh /usr/local/bin/
WORKDIR /app/bxextensions
RUN mkdir release/
COPY release/MANIFEST.MF release/MANIFEST.MF
COPY build_extensions.py ./
COPY CMakeLists.txt ./
COPY tests tests

ENV PYTHONPATH=/app/bxextensions
ENV PYTHONS="python3"
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

