FROM python:3.7.0-alpine3.8

ARG GID=503
ARG UID=503

RUN adduser -S -u ${UID} -g ${GID} bxextensions && \
    mkdir -p /app/bxextensions && \
    chown -R ${UID}:${GID} /app/bxextensions

RUN apk update \
 && apk add --no-cache \
# grab su-exec for easy step-down from root
        'su-exec>=0.2' \
       tini \
# grab bash for the convenience
        bash \
# grab requirements for bxextenstions
        gcc libc-dev unixodbc-dev make \
       build-base \
    gfortran \
    python3 \
    libc6-compat \
    freetype-dev \
    openblas-dev \
    tcl \
    tk \
    python3-dev \
    pkgconfig \
    musl \
    libgfortran \
    libgcc \
       automake \
#      autogen \
       autoconf \
       libtool \
#      libtool-bin \
       openssl-dev \
       cmake \
       libexecinfo-dev

#upgrade pip
RUN pip3 install --upgrade pip setuptools

WORKDIR /app/bxextensions
COPY docker-entrypoint.sh /usr/local/bin/
COPY interface/ interface/
COPY lib/ lib/
COPY build_extensions.py ./
COPY CMakeLists.txt ./

RUN  chown -R ${UID}:${GID} /app/bxextensions


ENV PYTHONPATH=/app/bxextensions
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
