FROM centos:7 as builder

ARG GID=503
ARG UID=503

RUN if [ $(grep ":${GID}:" /etc/group | wc -l) == 0 ]; then groupadd --system --gid ${GID} bxextensions; fi

RUN if [ $(grep ":${UID}:" /etc/passwd | wc -l) == 0 ]; then useradd --uid ${UID} --system --gid ${GID} bxextensions; fi  && \
    mkdir -p /app/bxextensions && \
    chown -R ${UID}:${GID} /app/bxextensions

RUN yum -y update
RUN yum -y install yum-utils
RUN yum -y groupinstall development
RUN yum -y install https://repo.ius.io/ius-release-el7.rpm
RUN yum -y install python36-devel python36-pip
RUN yum -y install \
  libffi-devel \
  zlib-devel \
  bzip2-devel \
  openssl-devel \
  ncurses-devel \
  sqlite-devel \
  readline-devel \
  tk-devel \
  gdbm-devel \
  db4-devel \
  libpcap-devel \
  xz-devel \
  expat-devel \
  postgresql-devel \
  wget
RUN yum -y install cmake3

#install python 3.7.3
WORKDIR /usr/src 
RUN wget https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tgz 
RUN tar xzf Python-3.7.3.tgz 
WORKDIR /usr/src/Python-3.7.3 
RUN ./configure --enable-optimizations 
RUN make altinstall

#install python 3.8
WORKDIR /usr/src
RUN wget https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tgz
RUN tar xzf Python-3.8.3.tgz
WORKDIR /usr/src/Python-3.8.3
RUN ./configure --enable-optimizations
RUN make altinstall

RUN ln -s /usr/bin/cmake3 /usr/bin/cmake
RUN yum -y install centos-release-scl devtoolset-7-gcc
RUN yum -y install centos-release-scl-rh
RUN yum -y --enablerepo=centos-sclo-rh-testing install devtoolset-7-gcc devtoolset-7-gcc-c++
RUN /opt/rh/devtoolset-7/enable
RUN g++ --version

#upgrade pip
RUN pip3.8 install --upgrade pip setuptools

WORKDIR /app/bxextensions
RUN mkdir release/
COPY release/MANIFEST.MF release/MANIFEST.MF
COPY interface/ interface/
COPY lib/ lib/
COPY build_extensions.py ./
COPY CMakeLists.txt ./
COPY build/centos-7 build/local

WORKDIR /app/bxextensions/lib/third_party/libsodium-stable
RUN autoreconf --force --install
WORKDIR /app/bxextensions

RUN chown -R ${UID}:${GID} /app/bxextensions

ENV PYTHONPATH=/app/bxextensions
ENV CXX=/opt/rh/devtoolset-7/root/usr/bin/g++ CC=/opt/rh/devtoolset-7/root/usr/bin/gcc
ENV PYTHONS="/usr/local/bin/python3.7 /usr/local/bin/python3.8 python3"

RUN echo "build extensions $TAG for centos-7"
RUN cd /app/bxextensions && \
    PYTHON_VER=3.6 /usr/bin/python3.6 build_extensions.py --build-type Debug --src-dir /app/bxextensions --package-installation --no-cache && \
    PYTHON_VER=3.7 /usr/local/bin/python3.7 build_extensions.py --build-type Debug --src-dir /app/bxextensions --package-installation --no-cache && \
    PYTHON_VER=3.8 /usr/local/bin/python3.8 build_extensions.py --build-type Debug --src-dir /app/bxextensions --package-installation --no-cache && \
    mkdir -p /app/bxextensions/release/lib/ && cp -r ./*.so /app/bxextensions/release/lib/

FROM scratch AS export-stage
COPY --from=builder /app/bxextensions/release/lib/ /release_tag/centos-7
COPY --from=builder /app/bxextensions/build/local/ /build/centos-7