FROM ubuntu:18.04 as builder

ARG GID=503
ARG UID=503

RUN if [ $(grep ":${GID}:" /etc/group | wc -l) == 0 ]; then addgroup -system -gid ${GID} bxextensions; fi

RUN if [ $(grep ":${UID}:" /etc/passwd | wc -l) == 0 ]; then adduser -uid ${UID} -system -gid ${GID} bxextensions; fi  && \
    mkdir -p /app/bxextensions && \
    chown -R ${UID}:${GID} /app/bxextensions

RUN apt update \
 && apt upgrade -y \
 && apt install -y software-properties-common \
 && add-apt-repository -y ppa:deadsnakes/ppa

RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
RUN apt install -y tzdata

RUN apt install -y  \
# grab su-exec for easy step-down from root
       git \
# grab bash for the convenience
       bash \
# grab requirements for bxextenstions
       gcc libc-dev make \
       build-essential \
       gfortran \
       libfreetype6-dev \
       libopenblas-dev \
       tcl \
       tk \
       python3 \
       python3-pip \
       python3-dev \
       musl \
       automake \
       autoconf \
       libtool \
       libssl-dev \
       cmake \
       libffi-dev \
       python3.7-dev \
       python3.8-dev

#upgrade pip
RUN pip3 install --upgrade pip setuptools

WORKDIR /app/bxextensions
COPY interface/ interface/
COPY lib/ lib/
COPY build_extensions.py ./
COPY CMakeLists.txt ./

RUN chown -R ${UID}:${GID} /app/bxextensions

ENV PYTHONPATH=/app/bxextensions
ENV PYTHONS="/usr/bin/python3.7 /usr/bin/python3.8 python3"

RUN cd /app/bxextensions && \
    /usr/bin/python3.6 build_extensions.py --build-type Debug --src-dir /app/bxextensions --package-installation --no-cache && \
    /usr/bin/python3.7 build_extensions.py --build-type Debug --src-dir /app/bxextensions --package-installation --no-cache && \
    /usr/bin/python3.8 build_extensions.py --build-type Debug --src-dir /app/bxextensions --package-installation --no-cache && \
    mkdir -p /app/bxextensions/release/lib/ && cp -r ./*.so /app/bxextensions/release/lib/

FROM scratch AS export-stage
COPY --from=builder /app/bxextensions/release/lib/ /
