#ifndef UTILS_COMMON_TX_STATUS_CONSTS_H
#define UTILS_COMMON_TX_STATUS_CONSTS_H

#define TX_STATUS_IGNORE_SEEN 1 << 0
#define TX_STATUS_MSG_HAS_SHORT_ID 1 << 1
#define TX_STATUS_MSG_HAS_CONTENT 1 << 2
#define TX_STATUS_MSG_NO_CONTENT 1 << 3
#define TX_STATUS_MSG_NO_SHORT_ID 1 << 4
#define TX_STATUS_SEEN_SHORT_ID 1 << 5
#define TX_STATUS_SEEN_HASH 1 << 6
#define TX_STATUS_SEEN_CONTENT 1 << 7
#define TX_STATUS_SEEN_REMOVED_TRANSACTION 1 << 8
#define TX_STATUS_TIMED_OUT 1 << 9

#define MAX_NUM_SIZE 256

#endif //UTILS_COMMON_TX_STATUS_CONSTS_H
