#ifndef UTILS_COMMON_TX_VALIDATION_STATUS_CONSTS_H
#define UTILS_COMMON_TX_VALIDATION_STATUS_CONSTS_H

#define TX_VALIDATION_STATUS_VALID_TX 1 << 0
#define TX_VALIDATION_STATUS_INVALID_FORMAT 1 << 1
#define TX_VALIDATION_STATUS_INVALID_SIGNATURE 1 << 2
#define TX_VALIDATION_STATUS_INVALID_LOW_FEE 1 << 3


#endif //UTILS_COMMON_TX_VALIDATION_STATUS_CONSTS_H
