
#ifndef TPE_CONSTS_H_
#define TPE_CONSTS_H_

#define PLAIN_TEXT_DEFAULT_BUFFER_SIZE 4 * 1024 * 1024
#define BTC_DEFAULT_MINIMAL_SUB_TASK_TX_COUNT 2500
#define BTC_DEFAULT_TX_BUCKET_SIZE 10000
#define NULL_TX_SID 0
#define ALLOWED_TIME_REUSE_SENDER_NONCE 2
#define ALLOWED_GAS_PRICE_CHANGE_FACTOR_REUSE_SENDER_NONCE 1.1


#define ONT_DEFAULT_MINIMAL_SUB_TASK_TX_COUNT 2500

#endif /* TPE_CONSTS_H_ */
