
#ifndef TPE_CONSTS_H_
#define TPE_CONSTS_H_

#define PLAIN_TEXT_DEFAULT_BUFFER_SIZE 4 * 1024 * 1024

#define BC_DEFAULT_BLOCK_SIZE 112 + 10000 * 5

#define BC_TX_COUNT_OFFSET 104

#define BC_TX_SEGWIT_FLAG_VALUE 1



#endif /* TPE_CONSTS_H_ */
