#ifndef UTILS_PROTOCOLS_BLOCKCHAIN_PROTOCOL_NAME_H
#define UTILS_PROTOCOLS_BLOCKCHAIN_PROTOCOL_NAME_H

#define BLOCKCHAIN_PROTOCOL_BITCOIN_CASH "bitcoincash"
#define BLOCKCHAIN_PROTOCOL_BITCOIN "bitcoin"
#define BLOCKCHAIN_PROTOCOL_ETHEREUM "ethereum"
#define BLOCKCHAIN_PROTOCOL_ONTOLOGY "ontology"

#endif //UTILS_PROTOCOLS_BLOCKCHAIN_PROTOCOL_NAME_H


