
#ifndef UTILS_PROTOCOLS_ONTOLOGY_ONT_CONSTS_H_
#define UTILS_PROTOCOLS_ONTOLOGY_ONT_CONSTS_H_

#define ONT_TX_DEPLOY_TYPE_INDICATOR 0xD0
#define ONT_TX_INVOKE_TYPE_INDICATOR 0xD1
#define ONT_HDR_COMMON_OFF 24
#define ONT_TX_VERSION_SIZE 4
#define ONT_PREV_BLOCK_OFF ONT_HDR_COMMON_OFF + ONT_TX_VERSION_SIZE
#define ONT_BLOCK_TIME_HEIGHT_CONS_DATA_LEN 16
#define ONT_BLOCK_NEXT_BOOKKEEPER_LEN 20
#define ONT_BOOKKEEPER_LEN 33
#define ONT_DEFAULT_TX_COUNT 10000
#define ONT_DEFAULT_TX_SIZE 62
#define ONT_DEFAULT_BLOCK_SIZE 112 + ONT_DEFAULT_TX_COUNT * ONT_DEFAULT_TX_SIZE
#define ONT_BLOCK_LENGTH_OFFSET 16
#define ONT_BX_MERKLE_ROOT_OFFSET 9


#endif //UTILS_PROTOCOLS_ONTOLOGY_ONT_CONSTS_H_
